profile:
  type: array
  x-key: template-name
  items:
    oneOf:
      - description: 'applicationTemplate'
        type: object
        required:
          - template-name
          - category
          - manager-ip-address
          - manager-port
          - list-applications-service
          - list-management-domain-interfaces-service
          - inform-about-management-domain-interface-service
          - update-management-domain-interface-service
        properties:
          template-name:
            type: string
            description: >
              'applicationTemplateName
              candidate: from [CDM://v1/create-application-template$request.body#application-template-name]
              running: from candidate
              operational: ./. - does not exist in OperationalDS as it cannot be measured'
          category:
            type: string
            enum:
              - 'application'
          manager-ip-address:
            type: string
            description: >
              'IP address of the ApplicationDomainManager (ADM)
              candidate: from [CDM://v1/create-application-template$request.body#manager-ip-address]
              running: from candidate
              operational: ./.'
          manager-port:
            type: string
            description: >
              'TCP port of the ADM
              candidate: from [CDM://v1/create-application-template$request.body#manager-port]
              running: from candidate
              operational: ./.'
          list-applications-service:
            type: string
            description: >
              'Service for providing the list of applications at ADM
              RequestBody: none
              ResponseBody: {list-of-application-names:string[*]}
              candidate: from [CDM://v1/create-application-template$request.body#list-applications-service]
              running: from candidate
              operational: ./.'
          list-management-domain-interfaces-service:
            type: string
            description: >
              'Service for providing the list of management domains of an application at ADM
              RequestBody: {application-name:string}
              ResponseBody: {list-of-management-domains:string[*]}
              candidate: from [CDM://v1/create-application-template$request.body#list-management-domain-interfaces-service]
              running: from candidate
              operational: ./.'
          inform-about-management-domain-interface-service:
            type: string
            description: >
              'Service for providing configuration information of a management domain at an application at ADM
              RequestBody: {application-name:string; management-domain-name:string}
              ResponseBody: {remote-ip-address:string; remote-port:integer}
              candidate: from [CDM://v1/create-application-template$request.body#inform-about-management-domain-interface-service]
              running: from candidate
              operational: ./.'
          update-management-domain-interface-service:
            type: string
            description: >
              'Service for updating the configuration of a management domain at an application at ADM
              RequestBody: {application-name:string; management-domain-name:string; remote-ip-address:string; remote-port:integer}
              ResponseBody: none
              candidate: from [CDM://v1/create-application-template$request.body#update-management-domain-interface-service]
              running: from candidate
              operational: ./.'

          # Please add, remove and change the parameters that need to be managed by template here
