profile:
  type: array
  x-key: template-name
  items:
    oneOf:
      - description: 'applicationTemplate'
        type: object
        required:
          - template-name
          - category
          - manager-ip-address
          - manager-port
          - measure-list-of-management-domain-interfaces-function-name
          - reconstruct-management-domain-interfaces-function-name
        properties:
          template-name:
            type: string
            description: >
              'applicationTemplateName
              candidate: from [CDM://v1/create-application-template$request.body#application-template-name]
              running: from candidate
              operational: from running'
          category:
            type: string
            enum:
              - 'application'
          manager-ip-address:
            type: string
            description: >
              'IP address of the ApplicationDomainManager (ADM)
              candidate: from [CDM://v1/create-application-template$request.body#manager-ip-address]
              running: from candidate
              operational: from running'
          manager-port:
            type: integer
            description: >
              'TCP port of the ADM
              candidate: from [CDM://v1/create-application-template$request.body#manager-port]
              running: from candidate
              operational: from running'
          measure-list-of-management-domain-interfaces-function-name:
            type: string
            description: >
              'Function for providing configuration information of a management domain at an application at ADM
              candidate: from [CDM://v1/create-application-template$request.body#measure-list-of-management-domain-interfaces-function-name]
              running: from candidate
              operational: from running'
            example: 'p1MeasureListOfManagementDomainInterfaces'
          reconstruct-management-domain-interfaces-function-name:
            type: string
            description: >
              'Function for updating the configuration of a management domain at an application at ADM
              candidate: from [CDM://v1/create-application-template$request.body#reconstruct-management-domain-interfaces-function-name]
              running: from candidate
              operational: from running'
            example: 'p1ReconstructManagementDomainInterface'
