control-construct:
  type: array
  x-key: element-name
  items:
    oneOf:
      - description: 'application'
        type: object
        required:
          - element-name
          - category
          - _template
          - logical-termination-point
        properties:
          element-name:
            type: string
            description: >
              'applicationName
              candidate: from [CDM://v1/regard-application$request.body#application-name]
              running: from candidate
              operational: from running; entire CC to be deleted, if applicationName not included in [[/network-control-domain=running/profile=[_template]/list-applications-service]$response.body#list-of-application-names]'
          category:
            type: string
            enum:
              - 'application'
          _template:
            type: string
            description: >
              'applicationTemplateName
              Reference towards an entry in the list of Profiles
              Both instances of ControlConstruct and Profile must have an identical value in their category attributes
              candidate: from [CDM://v1/regard-application$request.body#application-template-name]
              running: from candidate
              operational: ./. - does not exist in OperationalDS as it cannot be read from the real element'
          logical-termination-point:
            type: array
            x-key: local-id
            items:
              oneOf:
                - description: 'LogicalTerminationPoint - see 12_ManagementDomainInterface.yaml'
                  type: object
