openapi: 3.0.0
info:
  title: nginx
  version: 1.0.0
  description: MeasurementFunctions and ImplementationFunctions at the nginx LoadBalancer

paths:
########################################################################################################################
#   Measurement and Implementation
########################################################################################################################


########################################################################################################################
#   Common Components
########################################################################################################################
components:
